### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by chenshijin1** [rick0000/mjaigym#2]
Hello, what is the running environment of this project? 
What is the version of Linux? 
The version of pytorch?

**Comment by rick0000** [comment]
Hi chenshijin1,
This code works on Ubuntu 18.04, 20.04, Google Colaboratory
and PyTorch version 1.6.x (upper PyTorch versions are not checked)

If you only use mjaigym module like as follow sample, PyTorch is not needed.
https://colab.research.google.com/drive/1mDlIQU06frYpvpgNS5-44Ur3lVhr1nrt?usp=sharing#scrollTo=U4iubgUJGCm7

**Comment by chenshijin1** [comment]
> Hi chenshijin1,
> This code works on Ubuntu 18.04, 20.04, Google Colaboratory
> and PyTorch version 1.6.x (upper PyTorch versions are not checked)
> 
> If you only use mjaigym module like as follow sample, PyTorch is not needed.
> https://colab.research.google.com/drive/1mDlIQU06frYpvpgNS5-44Ur3lVhr1nrt?usp=sharing#scrollTo=U4iubgUJGCm7

Thank you very much, your project is great.
